[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ex2 = "C4pWBtp5XttdUfeDqYu3gLhpuPardmZKXtFiXK7wk86i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/fox/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
